apiVersion: v1
kind: DeploymentConfig
metadata:
  name: externalized-app
  namespace: ext-proj
  selfLink: /oapi/v1/namespaces/ext-proj/deploymentconfigs/externalized-app
  uid: bf891745-0eb8-11e7-ad3e-32d9e461c853
  resourceVersion: '6998'
  generation: 6
  creationTimestamp: '2017-03-22T04:33:50Z'
  labels:
    app: externalized-app
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources: {}
  triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - externalized-app
        from:
          kind: ImageStreamTag
          namespace: ext-proj
          name: 'externalized-app:2.0'
        lastTriggeredImage: >-
          172.30.238.7:5000/ext-proj/externalized-app@sha256:ac0a963fb8b73ba1f3402740ca012ae390e59dbcbd6078b79684d516fb004702
    - type: ConfigChange
  replicas: 1
  test: false
  selector:
    app: externalized-app
    deploymentconfig: externalized-app
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: externalized-app
        deploymentconfig: externalized-app
      annotations:
        openshift.io/container.externalized-app.image.entrypoint: '["catalina.sh","run"]'
        openshift.io/generated-by: OpenShiftNewApp
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: ext-config-map
            items:
              - key: app.properties
                path: app.properties
            defaultMode: 420
      containers:
        - name: externalized-app
          image: >-
            172.30.238.7:5000/ext-proj/externalized-app@sha256:ac0a963fb8b73ba1f3402740ca012ae390e59dbcbd6078b79684d516fb004702
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: APP_CONFIG_LOCATION
              value: /etc/app-config-map-source
          resources: {}
          volumeMounts:
            - name: config-volume
              mountPath: /etc/app-config-map-source
          terminationMessagePath: /dev/termination-log
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
status:
  latestVersion: 3
  observedGeneration: 6
  replicas: 1
  updatedReplicas: 1
  availableReplicas: 1
  details:
    message: config change
    causes:
      - type: ConfigChange
  conditions:
    - type: Available
      status: 'True'
      lastTransitionTime: '2017-03-22T04:33:55Z'
      message: Deployment config has minimum availability.
    - type: Progressing
      status: 'True'
      lastTransitionTime: '2017-03-22T04:42:33Z'
      reason: NewReplicationControllerAvailable
      message: Replication controller "externalized-app-3" has completed progressing
